name: test
url: https://github.com/acocac/scivision-treecrown-plugin
import: scivision_treecrown_plugin
model: DetectreeRGB
args:
    model_source: zenodo
prediction_fn:
    call: predict
    args:
        X: image
    kwargs: None