channels:
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib
  - pytorch==1.9.0
  - torchvision==0.10.0
  - urllib3
  - pip
  - pip:
      - git+https://github.com/facebookresearch/detectron2.git